[Backend errors detected]
disabled = 0
search = index=teachua_k8s kubernetes.container_name=backend ("ERROR" OR "Exception")
dispatch.earliest_time = -5m
dispatch.latest_time = now
cron_schedule = */5 * * * *
enableSched = 1
counttype = number of events
relation = greater than
quantity = 0
alert.severity = 4
alert.suppress = 0
alert.track = 1

[No backend logs]
disabled = 0
search = index=teachua_k8s kubernetes.container_name=backend | stats count | search count=0
dispatch.earliest_time = -10m
dispatch.latest_time = now
cron_schedule = */10 * * * *
enableSched = 1
counttype = number of events
relation = greater than
quantity = 0
alert.severity = 5
alert.suppress = 0
alert.track = 1

[Frontend 5xx errors]
disabled = 0
search = index=teachua_k8s kubernetes.container_name=frontend status>=500
dispatch.earliest_time = -5m
dispatch.latest_time = now
cron_schedule = */5 * * * *
enableSched = 1
counttype = number of events
relation = greater than
quantity = 0
alert.severity = 4
alert.suppress = 0
alert.track = 1
