apiVersion: v1
kind: ConfigMap
metadata: 
  name: backend-config
  namespace: teachua
data:
  JDBC_DRIVER: com.mysql.cj.jdbc.Driver
  DATASOURCE_URL: jdbc:mysql://mysql:3306/teachua2?useUnicode=true&serverTimezone=UTC