apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: teachua
type: Opaque
stringData:
  DATASOURCE_USER: teachua_user
  DATASOURCE_PASSWORD: teachua_password
  JWT_SECRET: change-this-secret-later