apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: teachua
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 441955873558.dkr.ecr.eu-north-1.amazonaws.com/teachua-dev-backend:810f7b3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret