apiVersion: v1
kind: Secret
metadata: 
  name: mysql-secret
  namespace: teachua
type: Opaque
stringdata:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: teachua2
  MYSQL_USER: teachua_user
  MYSQL_PASSWORD: teachua_password