---
- name: Provision monitoring EC2 instance
  hosts: monitoring
  become: true

  roles:
    - common
    - splunk

- name: Provision EC2 instance
  hosts: app
  become: true

  roles:
    - common
    - docker
    - k3s_prerequisites
    - k3s
    - splunk_forwarder
